Add check for quotes in Yaml files
these break JSON payload for Ayrshare API calls

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -36,6 +36,21 @@ jobs:
             fi
         done
 
+  no_quotes_in_yaml_file:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Check for quotes in Yaml
+      run: |
+        for FACT_YAML in $(find -name info.yaml); do
+            if grep '"' $FACT_YAML; then
+                echo "FAIL: Double quotes found in $FACT_YAML"
+                exit 1
+            fi
+        done
+
   image_is_600x600:
     runs-on: ubuntu-latest
     strategy:
